### ISSUE TITLE
Consider changing the project name

### ISSUE THREAD

**Issue by zachleat** [djbclark/chrome-schismator#3]
I posted a tweet about this project today, I’ve been using it this week and really love it so far. However, the feedback I’m seeing (and I would echo it) would be that this project should have a different name. If you’d like help brainstorming a new one, let me know I’d be glad to help! 

https://twitter.com/zachleat/status/710501306557857792

My naming repertoire includes `parseIntimate` (http://www.zachleat.com/parseintimate/), `A Font Garde` (https://github.com/filamentgroup/a-font-garde), and `tablesaw` (https://github.com/filamentgroup/tablesaw), among others. I think we can find something better here.

Thanks—great project!

**Comment by djbclark** [comment]
I'd be happy to. I agree in hindsight that the name is only agreeable to those like myself with a dark sense of humor. 

For the moment, I'll change it to chrome-schismator.

I'm totally not attached to that. **Suggestions would be much appreciated.**
